# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeData',
            fields=[
                ('pincode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('pincode_success_rate', models.FloatField(default=1.0)),
                ('pincode_successful_transactions', models.IntegerField(default=0)),
                ('pincode_total_trasactions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInputModel',
            fields=[
                ('user_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_succesful_transactions', models.IntegerField(default=0)),
                ('user_total_transactions', models.IntegerField(default=0)),
                ('user_success_rate', models.FloatField(default=1.0)),
                ('user_theft', models.BooleanField(default=False)),
            ],
        ),
    ]
